admin:
  password: ${ADMIN_PASSWORD}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
    properties:
      hibernate.jdbc.time_zone: UTC
  rest:
    connection-timeout: 3000
    read-timeout: 5000
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.perplexity.ai
      chat:
        completions-path: /chat/completions
        options:
          model: sonar-pro
          temperature: 0.7
      embedding:
        enabled: false
  redis:
    data:
      redis:
        host: redis
        port: 6379

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}

kma:
  api:
    key: ${KMA_API_KEY}

springdoc:
  swagger-ui:
    path: /api-docs
  api-docs:
    path: /v3/api-docs

